version: '3'

services:
  shell:
    links:
      - microfrontend_main
      - microfrontend_norouting 
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shell
    ports:
      - "5000:4000"

  microfrontend_main:
    build:
      context: .
      dockerfile: Dockerfile.main
    container_name: microfrontend_main
  
  microfrontend_norouting:
    build:
      context: .
      dockerfile: Dockerfile.norouting
    container_name: microfrontend_norouting
